apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oai-tcpdump-pv-claim
  namespace: oai-cn5g
spec:
  storageClassName: rook-ceph-fs-simple
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi