apiVersion: v1

kind: PersistentVolume

metadata:

  name: free5gc-mongodb-pv

spec:

  accessModes:

    - ReadWriteMany

  capacity:

    storage: 100Mi

  storageClassName: standard

  hostPath:

    path: /users/eriksilv/free5gc-mongodb-pv
