apiVersion: v1

kind: PersistentVolume

metadata:

  name: open5gs-mongodb-pv

spec:

  accessModes:

    - ReadWriteMany

      
  capacity:

    storage: 100Mi

    #storageclass.kubernetes.io/is-default-class: true

  storageClassName: default

  hostPath:

    path: /users/eriksilv/open5gs-mongodb-pv
