apiVersion: v1

kind: PersistentVolume

metadata:

  name: open5gs-mongodb-pv

spec:

  accessModes:

    - ReadWriteMany

  capacity:

    storage: 100Mi

  storageClassName: standard

  hostPath:

    path: /users/eriksilv/open5gs-mongodb-pv
