apiVersion: v1

kind: PersistentVolume

metadata:

  name: open5gs-mongodb-pv

spec:

  storageClassName: "manual"

  accessModes:

    - ReadWriteOnce
  
  #persistentVolumeReclaimPolicy: Retain

  nodeAffinity:

    required:

      nodeSelectorTerms:

      - matchExpressions:

        - key: kubernetes.io/hostname

          operator: In

          values:

          - worker1.helm16.ilabt-imec-be.wall2.ilabt.iminds.be  

  persistentVolumeReclaimPolicy: Recycle
      
  capacity:

    storage: 100Mi

  hostPath:

    path: /users/eriksilv/open5gs-mongodb-pv
