apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: free5gc-mongodb-pv
  namespace: free5gc
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
