apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: free5gc
data:
  nrfConfig.yaml: |
    info:
      version: 1.0.2
      description: NRF initial local configuration

    configuration:
      MongoDBName: free5gc # database name in MongoDB
      MongoDBUrl: mongodb://db:27017 # a valid URL of the mongodb
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: nrf.free5gc.svc.cluster.local
        bindingIPv4: 0.0.0.0
        port: 8000 # port used to bind the service
        tls: # the local path of TLS key
          pem: cert/nrf.pem # NRF TLS Certificate
          key: cert/nrf.key # NRF TLS Private key
      DefaultPlmnId:
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      serviceNameList: # the SBI services provided by this NRF, refer to TS 29.510
        - nnrf-nfm # Nnrf_NFManagement service
        - nnrf-disc # Nnrf_NFDiscovery service

    logger: # log output setting
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-nrf
  namespace: free5gc
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
      labels:
        epc-mode: nrf
        app: free5gc-nrf
        version: v3.3.0
        prometheus: free5gc-monitor
    spec:
      hostname: nrf-pod
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: metallica
      containers:
        - name: nrf
          image: free5gc/nrf:v3.3.0
          imagePullPolicy: Always
          command: ["./nrf", "-c", "/configuracoes/nrfConfig.yaml"]
          ports:
            - name: http2-8000
              protocol: TCP
              containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /configuracoes
      volumes:
        - name: config-volume
          configMap:
            name: nrf-config
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: nrf
  namespace: free5gc
spec:
  selector:
    epc-mode: nrf
    app: free5gc-nrf
  ports:
    - name: http2-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: free5gc-nrf
  namespace: free5gc
  labels:
    app: free5gc-nrf
spec:
  selector:
    matchLabels:
      app: free5gc-nrf
  endpoints:
  - interval: 30s
    port: http2-15090
---