apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: free5gc
spec:
  ports:
    - name: mongo-27017
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: free5gc-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-mongodb
  namespace: free5gc
spec:
  selector:
    matchLabels:
      app: free5gc-mongodb
  template:
    metadata:
      labels:
        app: free5gc-mongodb
        version: v4.4
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: free5gmano/nextepc-mongodb
        name: free5gc-mongodb
        ports:
          - name: mongo-27017
            protocol: TCP
            containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: free5gc-mongodb-pv-claim
