apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: cemenin
spec:
  ports:
  - port: 27017
    name: mongo-open5gs-27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
  namespace: cemenin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
        version: v4.4
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: worker1.helm16.ilabt-imec-be.wall2.ilabt.iminds.be
        #nodetype: server
      containers:
      - image: free5gmano/nextepc-mongodb
        name: open5gs-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        #command: ["sleep", "1d"]
        volumeMounts:
        - name: mongodb-persistent-storage # open5gs-mongodb-pv 
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage #  open5gs-mongodb-pv 
        persistentVolumeClaim:
          claimName:  mongodb-pv-claim
