apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-udm
  namespace: free5gc
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
        app: free5gc-udm
        version: v3.3.0
        prometheus: free5gc-monitor
    spec:
      hostname: udm-pod
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: metallica
      containers:
        - name: udm
          image: free5gc/udm:v3.3.0
          imagePullPolicy: Always
          command: ["./udm", "-c", "/configuracoes/udmConfig.yaml"]
          ports:
            - name: http2-8000
              protocol: TCP
              containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /configuracoes
      volumes:
        - name: config-volume
          configMap:
            name: udm-config
            defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: free5gc
data:
  udmConfig.yaml: |
    info:
      version: 1.0.3
      description: UDM initial local configuration
    configuration:
      serviceNameList: # the SBI services provided by this UDM, refer to TS 29.503
        - nudm-sdm # Nudm_SubscriberDataManagement service
        - nudm-uecm # Nudm_UEContextManagement service
        - nudm-ueau # Nudm_UEAuthenticationManagement service
        - nudm-ee # Nudm_EventExposureManagement service
        - nudm-pp # Nudm_ParameterProvisionDataManagement service
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: udm.free5gc.svc.cluster.local
        bindingIPv4: 0.0.0.0
        port: 8000 # Port used to bind the service
        tls: # the local path of TLS key
          pem: cert/udm.pem # UDM TLS Certificate
          key: cert/udm.key # UDM TLS Private key
      nrfUri: http://nrf.free5gc.svc.cluster.local:8000

      # test data set from TS33501-f60 Annex C.4
      SuciProfile: # Home Network Public Key ID = slice index +1
        - ProtectionScheme: 1 # Protect Scheme: Profile A
          PrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
          PublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        - ProtectionScheme: 2 # Protect Scheme: Profile B
          PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
          PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4

    logger: # log output setting
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false
---
apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: free5gc
spec:
  selector:
    epc-mode: udm
    app: free5gc-udm
  ports:
    - name: http2-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
---