apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-amf
  namespace: free5gc
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
        app: free5gc-amf
        version: v3.3.0
        prometheus: free5gc-monitor
    spec:
      hostname: amf-pod
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: amf
          image: free5gc/amf:v3.3.0
          imagePullPolicy: Always
          command: ["./amf", "-c" ,"/configuracoes/amfConfig.yaml"]
          ports:
            - name: http2-8000
              protocol: TCP
              containerPort: 8000
            - name: sctp-38412
              protocol: SCTP
              containerPort: 38412
          volumeMounts:
            - name: config-volume
              mountPath: /configuracoes
      volumes:
        - name: config-volume
          configMap:
            name: amf-config
            defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: free5gc
data:
  amfConfig.yaml: |
    info:
      version: 1.0.9
      description: AMF initial local configuration
    configuration:
      amfName: AMF
      ngapIpList:
        - amf-pod
      ngapPort: 38412
      sbi:
        scheme: http
        registerIPv4: amf.free5gc.svc.cluster.local
        bindingIPv4: 0.0.0.0
        port: 8000
        tls:
          pem: cert/amf.pem
          key: cert/amf.key
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 000001
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
      nrfUri: http://nrf.free5gc.svc.cluster.local:8000
      security:
        integrityOrder:
          - NIA2
        cipheringOrder:
          - NEA0
      networkName:
        full: free5GC
        short: free
      ngapIE:
        mobilityRestrictionList:
          enable: true
        maskedIMEISV:
          enable: true
        redirectionVoiceFallback:
          enable: false
      nasIE:
        networkFeatureSupport5GS:
          enable: true
          length: 1
          imsVoPS: 0
          emc: 0
          emf: 0
          iwkN26: 0
          mpsi: 0
          emcN3: 0
          mcsi: 0
      t3502Value: 720
      t3512Value: 3600
      non3gppDeregTimerValue: 3240
      t3513:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3522:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3550:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3555:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3560:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3565:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      t3570:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      locality: area1
      sctp:
        numOstreams: 3
        maxInstreams: 5
        maxAttempts: 2
        maxInitTimeout: 2
      defaultUECtxReq: false

    logger:
      enable: true
      level: info
      reportCaller: false
---
apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: free5gc
spec:
  selector:
    epc-mode: amf
    app: free5gc-amf
  ports:
    - name: http2-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: sctp-38412
      protocol: SCTP
      port: 38412
      targetPort: 38412
---
