apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-mongodb-pv
  namespace: cemenin
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
